import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import "./globals.css";
import AppProviders from "@/providers/AppProviders";
import LocaleSwitcher from "@/components/atoms/LocalSwitcher";
import { changeLocaleAction } from "@/i18n/locale";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <NextIntlClientProvider>
            
            {children}
            <LocaleSwitcher changeLocaleAction={changeLocaleAction}/>
            </NextIntlClientProvider>
            
        </AppProviders>
        
      </body>
    </html>
  );
}
